# Generated by Django 6.0.3 on 2026-04-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_internship_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('remote', 'Work From Home')], default='full_time', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_type',
            field=models.CharField(choices=[('year', 'Per Year'), ('month', 'Per Month')], default='year', max_length=10),
        ),
    ]
