# Generated by Django 6.0.3 on 2026-04-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_job_type_job_salary_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='duration_months',
        ),
        migrations.AddField(
            model_name='internship',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='stipend',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
