# Generated by Django 6.0.3 on 2026-04-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_internship_duration_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='job_type',
            field=models.CharField(choices=[('WFH', 'Work From Home'), ('ONSITE', 'Onsite / Location Based')], default='ONSITE', max_length=10),
        ),
    ]
