# Generated by Django 6.0.3 on 2026-04-14 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_internship_job_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='job_type',
        ),
        migrations.AddField(
            model_name='internship',
            name='internship_type',
            field=models.CharField(choices=[('onsite', 'Onsite'), ('wfh', 'Work From Home')], default='onsite', max_length=10),
        ),
        migrations.AlterField(
            model_name='internship',
            name='description',
            field=models.TextField(default='No description provided'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internship',
            name='duration',
            field=models.CharField(default='No description provided', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internship',
            name='stipend',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='resumes/')),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.internship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
