# Generated by Django 6.0.3 on 2026-04-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_remove_internship_job_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
