# Generated by Django 6.0.3 on 2026-04-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_application_internship_application_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipapplication',
            name='internship',
        ),
        migrations.RemoveField(
            model_name='internshipapplication',
            name='user',
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
