# Generated by Django 6.0.3 on 2026-04-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_internshipapplication_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipapplication',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
