# Generated by Django 6.0.3 on 2026-04-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_profile_email_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary_type',
            field=models.CharField(choices=[('year', 'Per Year'), ('month', 'Per Month')], default='year', max_length=20),
        ),
    ]
